openapi: 3.0.3
info:
  title: JIZT API
  description: >
    JIZT API provides an easy way of summarizing your text
    using state-of-the-art NLP models.
  contact:
    name: Diego Miguel
    url: 'https://www.jizt.it'
    email: jizt@diegomiguel.me
  license:
    name: GPL-3.0 License
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
  version: 0.1.0
tags:
  - name: Summaries
    description: Summarization tools.
servers:
  - url: 'https://api.jizt.it/v1'
    description: The API server
paths:
  /summaries/plain-text:
    $ref: 'paths/summaries/plain-text.yaml'
  /summaries/plain-text/{summaryId}:
    $ref: 'paths/summaries/plain-text@{summaryId}.yaml'
  /healthz:
    $ref: 'paths/summaries/healthz.yaml'

# Useful links:
# - https://github.com/APIs-guru/openapi-directory/blob/master/APIs/anchore.io/0.1.16/openapi.yaml
# - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md
# - https://redoc.ly/docs/resources/learning-openapi/
